version: 0.0
os: linux

files:
  - source: ./
    destination: /opt/codedeploy-agent

hooks:
  ApplcationStop:
   - location: ./applicationStop.sh
     timeout: 300
     runas : ubuntu

  AfterInstall:
    - location: ./afterInstall.sh
      timeout: 300
      runas : ubuntu

  ApplicationStart:
    - location: ./applicationStart.sh
      timeout: 300
      runas: ubuntu